# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Rose Tutor Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rose Tutor Tracker
  pod 'Rosefire', :git => 'https://ada.csse.rose-hulman.edu/rosefire/ios-sdk.git'
end
